-- Workspace A11Y retrieval (post-evaluation product implementation)
-- This schema is intentionally separate from the Master thesis prototype.
-- It stores an exported copy of normative corpus entries for lightweight server-side retrieval.

create extension if not exists pg_trgm;

create table if not exists public.workspace_a11y_corpus (
  id bigint generated by default as identity primary key,
  standard text not null check (standard in ('RGAA', 'RAAM')),
  version text,
  reference text not null,
  reference_type text,
  title text,
  content text not null,
  document text,
  page integer,
  keywords text not null default '',
  source_origin text not null default 'workspace-post-evaluation',
  created_at timestamptz not null default now(),
  search_vector tsvector generated always as (
    to_tsvector(
      'simple',
      coalesce(standard, '') || ' ' ||
      coalesce(reference, '') || ' ' ||
      coalesce(reference_type, '') || ' ' ||
      coalesce(title, '') || ' ' ||
      coalesce(keywords, '') || ' ' ||
      coalesce(content, '')
    )
  ) stored
);

create unique index if not exists workspace_a11y_corpus_unique
  on public.workspace_a11y_corpus (standard, coalesce(version, ''), reference, coalesce(reference_type, ''), md5(content));

create index if not exists workspace_a11y_corpus_search_idx
  on public.workspace_a11y_corpus using gin (search_vector);

create index if not exists workspace_a11y_corpus_content_trgm_idx
  on public.workspace_a11y_corpus using gin (content gin_trgm_ops);

create index if not exists workspace_a11y_corpus_reference_trgm_idx
  on public.workspace_a11y_corpus using gin (reference gin_trgm_ops);

alter table public.workspace_a11y_corpus enable row level security;

-- Corpus is not directly readable from the public/authenticated browser API.
revoke all on public.workspace_a11y_corpus from anon, authenticated;
grant select, insert, update, delete on public.workspace_a11y_corpus to service_role;

create or replace function public.search_workspace_a11y(
  p_standard text,
  p_query text,
  p_limit integer default 8
)
returns table (
  id bigint,
  standard text,
  version text,
  reference text,
  reference_type text,
  title text,
  content text,
  document text,
  page integer,
  score double precision
)
language sql
stable
security definer
set search_path = public
as $$
  with q as (
    select websearch_to_tsquery('simple', coalesce(nullif(trim(p_query), ''), 'accessibilite')) as tsq,
           lower(coalesce(p_query, '')) as raw
  ),
  ranked as (
    select
      c.*,
      q.tsq,
      q.raw,
      (
        setweight(to_tsvector('simple', coalesce(c.standard, '') || ' ' || coalesce(c.reference, '') || ' ' || coalesce(c.reference_type, '') || ' ' || coalesce(c.title, '') || ' ' || coalesce(c.keywords, '')), 'A') ||
        setweight(to_tsvector('simple', coalesce(c.content, '')), 'B')
      ) as weighted_vector
    from public.workspace_a11y_corpus c
    cross join q
    where c.standard = upper(p_standard)
  )
  select
    r.id,
    r.standard,
    r.version,
    r.reference,
    r.reference_type,
    r.title,
    r.content,
    r.document,
    r.page,
    (
      5.0 * ts_rank_cd(r.weighted_vector, r.tsq) +
      4.0 * similarity(lower(coalesce(r.title, '')), r.raw) +
      1.2 * similarity(lower(coalesce(r.keywords, '')), r.raw) +
      0.35 * similarity(lower(r.content), r.raw) +
      case when lower(r.reference) = r.raw then 8.0 else 0.0 end +
      case when lower(coalesce(r.title, '')) like '%' || r.raw || '%' and length(r.raw) > 3 then 1.5 else 0.0 end
    )::double precision as score
  from ranked r
  where
    r.weighted_vector @@ r.tsq
    or similarity(lower(coalesce(r.title, '')), r.raw) > 0.06
    or similarity(lower(coalesce(r.keywords, '')), r.raw) > 0.05
    or similarity(lower(r.content), r.raw) > 0.04
    or lower(r.reference) = r.raw
  order by score desc, r.reference
  limit greatest(1, least(coalesce(p_limit, 8), 20));
$$;

revoke all on function public.search_workspace_a11y(text, text, integer) from public, anon, authenticated;
grant execute on function public.search_workspace_a11y(text, text, integer) to service_role;

comment on table public.workspace_a11y_corpus is
  'Post-evaluation workspace copy of normative corpus entries. Distinct from the frozen thesis prototype.';
