-- Workspace A11Y retrieval (post-evaluation product implementation)
-- This schema is intentionally separate from the Master thesis prototype.
-- It stores an exported copy of normative corpus entries for lightweight server-side retrieval.

create extension if not exists pg_trgm;

create table if not exists public.workspace_a11y_corpus (
  id bigint generated by default as identity primary key,
  standard text not null check (standard in ('RGAA', 'RAAM')),
  version text,
  reference text not null,
  reference_type text,
  title text,
  content text not null,
  document text,
  page integer,
  keywords text not null default '',
  source_origin text not null default 'workspace-post-evaluation',
  created_at timestamptz not null default now(),
  search_vector tsvector generated always as (
    to_tsvector(
      'simple',
      coalesce(standard, '') || ' ' ||
      coalesce(reference, '') || ' ' ||
      coalesce(reference_type, '') || ' ' ||
      coalesce(title, '') || ' ' ||
      coalesce(keywords, '') || ' ' ||
      coalesce(content, '')
    )
  ) stored
);

create unique index if not exists workspace_a11y_corpus_unique
  on public.workspace_a11y_corpus (standard, coalesce(version, ''), reference, coalesce(reference_type, ''), md5(content));

create index if not exists workspace_a11y_corpus_search_idx
  on public.workspace_a11y_corpus using gin (search_vector);

create index if not exists workspace_a11y_corpus_content_trgm_idx
  on public.workspace_a11y_corpus using gin (content gin_trgm_ops);

create index if not exists workspace_a11y_corpus_reference_trgm_idx
  on public.workspace_a11y_corpus using gin (reference gin_trgm_ops);

alter table public.workspace_a11y_corpus enable row level security;

-- Corpus is not directly readable from the public/authenticated browser API.
revoke all on public.workspace_a11y_corpus from anon, authenticated;
grant select, insert, update, delete on public.workspace_a11y_corpus to service_role;

create or replace function public.search_workspace_a11y(
  p_standard text,
  p_query text,
  p_limit integer default 8
)
returns table (
  id bigint,
  standard text,
  version text,
  reference text,
  reference_type text,
  title text,
  content text,
  document text,
  page integer,
  score double precision
)
language sql
stable
security definer
set search_path = public
as $$
  with q as (
    select websearch_to_tsquery('simple', coalesce(nullif(trim(p_query), ''), 'accessibilite')) as tsq,
           lower(coalesce(p_query, '')) as raw
  )
  select
    c.id,
    c.standard,
    c.version,
    c.reference,
    c.reference_type,
    c.title,
    c.content,
    c.document,
    c.page,
    (
      4.0 * ts_rank_cd(c.search_vector, q.tsq) +
      1.5 * similarity(lower(coalesce(c.title, '')), q.raw) +
      0.8 * similarity(lower(c.content), q.raw) +
      case when lower(c.reference) = q.raw then 5.0 else 0.0 end +
      case when lower(c.content) like '%' || q.raw || '%' and length(q.raw) > 3 then 0.7 else 0.0 end
    )::double precision as score
  from public.workspace_a11y_corpus c
  cross join q
  where c.standard = upper(p_standard)
    and (
      c.search_vector @@ q.tsq
      or similarity(lower(coalesce(c.title, '')), q.raw) > 0.08
      or similarity(lower(c.content), q.raw) > 0.04
      or lower(c.reference) = q.raw
    )
  order by score desc, c.reference
  limit greatest(1, least(coalesce(p_limit, 8), 20));
$$;

revoke all on function public.search_workspace_a11y(text, text, integer) from public, anon, authenticated;
grant execute on function public.search_workspace_a11y(text, text, integer) to service_role;

comment on table public.workspace_a11y_corpus is
  'Post-evaluation workspace copy of normative corpus entries. Distinct from the frozen thesis prototype.';
